input {
  file {
    path => "client.log"
    start_position => "beginning"
    codec => "json"
  }
}

filter {
  json {
    source => "message"
  }

  mutate {
    add_field => {
      "url" => "%{[url]}"
      "uuid" => "%{[uuid]}"
      "urlscan_response" => "%{[urlscan_response]}"
      "gsb_response" => "%{[gsb_response]}"
    }
  }
}

output {
  elasticsearch { # Update elasticsearch credentials
    hosts => ["http://hostname:9200"] 
    index => ""
  }
}